<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.example.uiteststudy.ExampleUnitTest" tests="4" skipped="0" failures="1" errors="0" timestamp="2022-02-23T13:40:29" hostname="yuhuigyeong-ui-MacBookPro.local" time="0.059">
  <properties/>
  <testcase name="plus_test" classname="com.example.uiteststudy.ExampleUnitTest" time="0.006"/>
  <testcase name="junit_test" classname="com.example.uiteststudy.ExampleUnitTest" time="0.0"/>
  <testcase name="truth_type_test" classname="com.example.uiteststudy.ExampleUnitTest" time="0.053">
    <failure message="expected to contain: [1, 2]&#10;but was            : [1, 2]" type="com.google.common.truth.AssertionErrorWithFacts">expected to contain: [1, 2]
but was            : [1, 2]
	at com.example.uiteststudy.ExampleUnitTest.truth_type_test(ExampleUnitTest.kt:48)
</failure>
  </testcase>
  <testcase name="multi_test" classname="com.example.uiteststudy.ExampleUnitTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
